//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatedatabaseUser) DeepCopyInto(out *PrivatedatabaseUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatedatabaseUser.
func (in *PrivatedatabaseUser) DeepCopy() *PrivatedatabaseUser {
	if in == nil {
		return nil
	}
	out := new(PrivatedatabaseUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivatedatabaseUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatedatabaseUserInitParameters) DeepCopyInto(out *PrivatedatabaseUserInitParameters) {
	*out = *in
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatedatabaseUserInitParameters.
func (in *PrivatedatabaseUserInitParameters) DeepCopy() *PrivatedatabaseUserInitParameters {
	if in == nil {
		return nil
	}
	out := new(PrivatedatabaseUserInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatedatabaseUserList) DeepCopyInto(out *PrivatedatabaseUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PrivatedatabaseUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatedatabaseUserList.
func (in *PrivatedatabaseUserList) DeepCopy() *PrivatedatabaseUserList {
	if in == nil {
		return nil
	}
	out := new(PrivatedatabaseUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivatedatabaseUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatedatabaseUserObservation) DeepCopyInto(out *PrivatedatabaseUserObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatedatabaseUserObservation.
func (in *PrivatedatabaseUserObservation) DeepCopy() *PrivatedatabaseUserObservation {
	if in == nil {
		return nil
	}
	out := new(PrivatedatabaseUserObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatedatabaseUserParameters) DeepCopyInto(out *PrivatedatabaseUserParameters) {
	*out = *in
	out.PasswordSecretRef = in.PasswordSecretRef
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatedatabaseUserParameters.
func (in *PrivatedatabaseUserParameters) DeepCopy() *PrivatedatabaseUserParameters {
	if in == nil {
		return nil
	}
	out := new(PrivatedatabaseUserParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatedatabaseUserSpec) DeepCopyInto(out *PrivatedatabaseUserSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatedatabaseUserSpec.
func (in *PrivatedatabaseUserSpec) DeepCopy() *PrivatedatabaseUserSpec {
	if in == nil {
		return nil
	}
	out := new(PrivatedatabaseUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatedatabaseUserStatus) DeepCopyInto(out *PrivatedatabaseUserStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatedatabaseUserStatus.
func (in *PrivatedatabaseUserStatus) DeepCopy() *PrivatedatabaseUserStatus {
	if in == nil {
		return nil
	}
	out := new(PrivatedatabaseUserStatus)
	in.DeepCopyInto(out)
	return out
}
