//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectUserS3Credential) DeepCopyInto(out *ProjectUserS3Credential) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectUserS3Credential.
func (in *ProjectUserS3Credential) DeepCopy() *ProjectUserS3Credential {
	if in == nil {
		return nil
	}
	out := new(ProjectUserS3Credential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectUserS3Credential) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectUserS3CredentialInitParameters) DeepCopyInto(out *ProjectUserS3CredentialInitParameters) {
	*out = *in
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectUserS3CredentialInitParameters.
func (in *ProjectUserS3CredentialInitParameters) DeepCopy() *ProjectUserS3CredentialInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectUserS3CredentialInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectUserS3CredentialList) DeepCopyInto(out *ProjectUserS3CredentialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProjectUserS3Credential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectUserS3CredentialList.
func (in *ProjectUserS3CredentialList) DeepCopy() *ProjectUserS3CredentialList {
	if in == nil {
		return nil
	}
	out := new(ProjectUserS3CredentialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectUserS3CredentialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectUserS3CredentialObservation) DeepCopyInto(out *ProjectUserS3CredentialObservation) {
	*out = *in
	if in.AccessKeyID != nil {
		in, out := &in.AccessKeyID, &out.AccessKeyID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InternalUserID != nil {
		in, out := &in.InternalUserID, &out.InternalUserID
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectUserS3CredentialObservation.
func (in *ProjectUserS3CredentialObservation) DeepCopy() *ProjectUserS3CredentialObservation {
	if in == nil {
		return nil
	}
	out := new(ProjectUserS3CredentialObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectUserS3CredentialParameters) DeepCopyInto(out *ProjectUserS3CredentialParameters) {
	*out = *in
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.UserID != nil {
		in, out := &in.UserID, &out.UserID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectUserS3CredentialParameters.
func (in *ProjectUserS3CredentialParameters) DeepCopy() *ProjectUserS3CredentialParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectUserS3CredentialParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectUserS3CredentialSpec) DeepCopyInto(out *ProjectUserS3CredentialSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectUserS3CredentialSpec.
func (in *ProjectUserS3CredentialSpec) DeepCopy() *ProjectUserS3CredentialSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectUserS3CredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectUserS3CredentialStatus) DeepCopyInto(out *ProjectUserS3CredentialStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectUserS3CredentialStatus.
func (in *ProjectUserS3CredentialStatus) DeepCopy() *ProjectUserS3CredentialStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectUserS3CredentialStatus)
	in.DeepCopyInto(out)
	return out
}
