//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectFailoverIPAttach) DeepCopyInto(out *ProjectFailoverIPAttach) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectFailoverIPAttach.
func (in *ProjectFailoverIPAttach) DeepCopy() *ProjectFailoverIPAttach {
	if in == nil {
		return nil
	}
	out := new(ProjectFailoverIPAttach)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectFailoverIPAttach) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectFailoverIPAttachInitParameters) DeepCopyInto(out *ProjectFailoverIPAttachInitParameters) {
	*out = *in
	if in.Block != nil {
		in, out := &in.Block, &out.Block
		*out = new(string)
		**out = **in
	}
	if in.ContinentCode != nil {
		in, out := &in.ContinentCode, &out.ContinentCode
		*out = new(string)
		**out = **in
	}
	if in.GeoLoc != nil {
		in, out := &in.GeoLoc, &out.GeoLoc
		*out = new(string)
		**out = **in
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.RoutedTo != nil {
		in, out := &in.RoutedTo, &out.RoutedTo
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectFailoverIPAttachInitParameters.
func (in *ProjectFailoverIPAttachInitParameters) DeepCopy() *ProjectFailoverIPAttachInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectFailoverIPAttachInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectFailoverIPAttachList) DeepCopyInto(out *ProjectFailoverIPAttachList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProjectFailoverIPAttach, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectFailoverIPAttachList.
func (in *ProjectFailoverIPAttachList) DeepCopy() *ProjectFailoverIPAttachList {
	if in == nil {
		return nil
	}
	out := new(ProjectFailoverIPAttachList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectFailoverIPAttachList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectFailoverIPAttachObservation) DeepCopyInto(out *ProjectFailoverIPAttachObservation) {
	*out = *in
	if in.Block != nil {
		in, out := &in.Block, &out.Block
		*out = new(string)
		**out = **in
	}
	if in.ContinentCode != nil {
		in, out := &in.ContinentCode, &out.ContinentCode
		*out = new(string)
		**out = **in
	}
	if in.GeoLoc != nil {
		in, out := &in.GeoLoc, &out.GeoLoc
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.Progress != nil {
		in, out := &in.Progress, &out.Progress
		*out = new(float64)
		**out = **in
	}
	if in.RoutedTo != nil {
		in, out := &in.RoutedTo, &out.RoutedTo
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.SubType != nil {
		in, out := &in.SubType, &out.SubType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectFailoverIPAttachObservation.
func (in *ProjectFailoverIPAttachObservation) DeepCopy() *ProjectFailoverIPAttachObservation {
	if in == nil {
		return nil
	}
	out := new(ProjectFailoverIPAttachObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectFailoverIPAttachParameters) DeepCopyInto(out *ProjectFailoverIPAttachParameters) {
	*out = *in
	if in.Block != nil {
		in, out := &in.Block, &out.Block
		*out = new(string)
		**out = **in
	}
	if in.ContinentCode != nil {
		in, out := &in.ContinentCode, &out.ContinentCode
		*out = new(string)
		**out = **in
	}
	if in.GeoLoc != nil {
		in, out := &in.GeoLoc, &out.GeoLoc
		*out = new(string)
		**out = **in
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.RoutedTo != nil {
		in, out := &in.RoutedTo, &out.RoutedTo
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectFailoverIPAttachParameters.
func (in *ProjectFailoverIPAttachParameters) DeepCopy() *ProjectFailoverIPAttachParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectFailoverIPAttachParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectFailoverIPAttachSpec) DeepCopyInto(out *ProjectFailoverIPAttachSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectFailoverIPAttachSpec.
func (in *ProjectFailoverIPAttachSpec) DeepCopy() *ProjectFailoverIPAttachSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectFailoverIPAttachSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectFailoverIPAttachStatus) DeepCopyInto(out *ProjectFailoverIPAttachStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectFailoverIPAttachStatus.
func (in *ProjectFailoverIPAttachStatus) DeepCopy() *ProjectFailoverIPAttachStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectFailoverIPAttachStatus)
	in.DeepCopyInto(out)
	return out
}
