//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectDatabaseOpensearchPattern) DeepCopyInto(out *ProjectDatabaseOpensearchPattern) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectDatabaseOpensearchPattern.
func (in *ProjectDatabaseOpensearchPattern) DeepCopy() *ProjectDatabaseOpensearchPattern {
	if in == nil {
		return nil
	}
	out := new(ProjectDatabaseOpensearchPattern)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectDatabaseOpensearchPattern) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectDatabaseOpensearchPatternInitParameters) DeepCopyInto(out *ProjectDatabaseOpensearchPatternInitParameters) {
	*out = *in
	if in.ClusterID != nil {
		in, out := &in.ClusterID, &out.ClusterID
		*out = new(string)
		**out = **in
	}
	if in.MaxIndexCount != nil {
		in, out := &in.MaxIndexCount, &out.MaxIndexCount
		*out = new(float64)
		**out = **in
	}
	if in.Pattern != nil {
		in, out := &in.Pattern, &out.Pattern
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectDatabaseOpensearchPatternInitParameters.
func (in *ProjectDatabaseOpensearchPatternInitParameters) DeepCopy() *ProjectDatabaseOpensearchPatternInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectDatabaseOpensearchPatternInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectDatabaseOpensearchPatternList) DeepCopyInto(out *ProjectDatabaseOpensearchPatternList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProjectDatabaseOpensearchPattern, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectDatabaseOpensearchPatternList.
func (in *ProjectDatabaseOpensearchPatternList) DeepCopy() *ProjectDatabaseOpensearchPatternList {
	if in == nil {
		return nil
	}
	out := new(ProjectDatabaseOpensearchPatternList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProjectDatabaseOpensearchPatternList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectDatabaseOpensearchPatternObservation) DeepCopyInto(out *ProjectDatabaseOpensearchPatternObservation) {
	*out = *in
	if in.ClusterID != nil {
		in, out := &in.ClusterID, &out.ClusterID
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MaxIndexCount != nil {
		in, out := &in.MaxIndexCount, &out.MaxIndexCount
		*out = new(float64)
		**out = **in
	}
	if in.Pattern != nil {
		in, out := &in.Pattern, &out.Pattern
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectDatabaseOpensearchPatternObservation.
func (in *ProjectDatabaseOpensearchPatternObservation) DeepCopy() *ProjectDatabaseOpensearchPatternObservation {
	if in == nil {
		return nil
	}
	out := new(ProjectDatabaseOpensearchPatternObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectDatabaseOpensearchPatternParameters) DeepCopyInto(out *ProjectDatabaseOpensearchPatternParameters) {
	*out = *in
	if in.ClusterID != nil {
		in, out := &in.ClusterID, &out.ClusterID
		*out = new(string)
		**out = **in
	}
	if in.MaxIndexCount != nil {
		in, out := &in.MaxIndexCount, &out.MaxIndexCount
		*out = new(float64)
		**out = **in
	}
	if in.Pattern != nil {
		in, out := &in.Pattern, &out.Pattern
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectDatabaseOpensearchPatternParameters.
func (in *ProjectDatabaseOpensearchPatternParameters) DeepCopy() *ProjectDatabaseOpensearchPatternParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectDatabaseOpensearchPatternParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectDatabaseOpensearchPatternSpec) DeepCopyInto(out *ProjectDatabaseOpensearchPatternSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectDatabaseOpensearchPatternSpec.
func (in *ProjectDatabaseOpensearchPatternSpec) DeepCopy() *ProjectDatabaseOpensearchPatternSpec {
	if in == nil {
		return nil
	}
	out := new(ProjectDatabaseOpensearchPatternSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectDatabaseOpensearchPatternStatus) DeepCopyInto(out *ProjectDatabaseOpensearchPatternStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectDatabaseOpensearchPatternStatus.
func (in *ProjectDatabaseOpensearchPatternStatus) DeepCopy() *ProjectDatabaseOpensearchPatternStatus {
	if in == nil {
		return nil
	}
	out := new(ProjectDatabaseOpensearchPatternStatus)
	in.DeepCopyInto(out)
	return out
}
