//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NashaPartitionSnapshot) DeepCopyInto(out *NashaPartitionSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NashaPartitionSnapshot.
func (in *NashaPartitionSnapshot) DeepCopy() *NashaPartitionSnapshot {
	if in == nil {
		return nil
	}
	out := new(NashaPartitionSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NashaPartitionSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NashaPartitionSnapshotInitParameters) DeepCopyInto(out *NashaPartitionSnapshotInitParameters) {
	*out = *in
	if in.PartitionName != nil {
		in, out := &in.PartitionName, &out.PartitionName
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NashaPartitionSnapshotInitParameters.
func (in *NashaPartitionSnapshotInitParameters) DeepCopy() *NashaPartitionSnapshotInitParameters {
	if in == nil {
		return nil
	}
	out := new(NashaPartitionSnapshotInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NashaPartitionSnapshotList) DeepCopyInto(out *NashaPartitionSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NashaPartitionSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NashaPartitionSnapshotList.
func (in *NashaPartitionSnapshotList) DeepCopy() *NashaPartitionSnapshotList {
	if in == nil {
		return nil
	}
	out := new(NashaPartitionSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NashaPartitionSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NashaPartitionSnapshotObservation) DeepCopyInto(out *NashaPartitionSnapshotObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.PartitionName != nil {
		in, out := &in.PartitionName, &out.PartitionName
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NashaPartitionSnapshotObservation.
func (in *NashaPartitionSnapshotObservation) DeepCopy() *NashaPartitionSnapshotObservation {
	if in == nil {
		return nil
	}
	out := new(NashaPartitionSnapshotObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NashaPartitionSnapshotParameters) DeepCopyInto(out *NashaPartitionSnapshotParameters) {
	*out = *in
	if in.PartitionName != nil {
		in, out := &in.PartitionName, &out.PartitionName
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NashaPartitionSnapshotParameters.
func (in *NashaPartitionSnapshotParameters) DeepCopy() *NashaPartitionSnapshotParameters {
	if in == nil {
		return nil
	}
	out := new(NashaPartitionSnapshotParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NashaPartitionSnapshotSpec) DeepCopyInto(out *NashaPartitionSnapshotSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NashaPartitionSnapshotSpec.
func (in *NashaPartitionSnapshotSpec) DeepCopy() *NashaPartitionSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(NashaPartitionSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NashaPartitionSnapshotStatus) DeepCopyInto(out *NashaPartitionSnapshotStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NashaPartitionSnapshotStatus.
func (in *NashaPartitionSnapshotStatus) DeepCopy() *NashaPartitionSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(NashaPartitionSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}
