//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Iploadbalancing) DeepCopyInto(out *Iploadbalancing) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Iploadbalancing.
func (in *Iploadbalancing) DeepCopy() *Iploadbalancing {
	if in == nil {
		return nil
	}
	out := new(Iploadbalancing)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Iploadbalancing) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IploadbalancingInitParameters) DeepCopyInto(out *IploadbalancingInitParameters) {
	*out = *in
	if in.IPLoadbalancing != nil {
		in, out := &in.IPLoadbalancing, &out.IPLoadbalancing
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IploadbalancingInitParameters.
func (in *IploadbalancingInitParameters) DeepCopy() *IploadbalancingInitParameters {
	if in == nil {
		return nil
	}
	out := new(IploadbalancingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IploadbalancingList) DeepCopyInto(out *IploadbalancingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Iploadbalancing, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IploadbalancingList.
func (in *IploadbalancingList) DeepCopy() *IploadbalancingList {
	if in == nil {
		return nil
	}
	out := new(IploadbalancingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *IploadbalancingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IploadbalancingObservation) DeepCopyInto(out *IploadbalancingObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IPLoadbalancing != nil {
		in, out := &in.IPLoadbalancing, &out.IPLoadbalancing
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IploadbalancingObservation.
func (in *IploadbalancingObservation) DeepCopy() *IploadbalancingObservation {
	if in == nil {
		return nil
	}
	out := new(IploadbalancingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IploadbalancingParameters) DeepCopyInto(out *IploadbalancingParameters) {
	*out = *in
	if in.IPLoadbalancing != nil {
		in, out := &in.IPLoadbalancing, &out.IPLoadbalancing
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IploadbalancingParameters.
func (in *IploadbalancingParameters) DeepCopy() *IploadbalancingParameters {
	if in == nil {
		return nil
	}
	out := new(IploadbalancingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IploadbalancingSpec) DeepCopyInto(out *IploadbalancingSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IploadbalancingSpec.
func (in *IploadbalancingSpec) DeepCopy() *IploadbalancingSpec {
	if in == nil {
		return nil
	}
	out := new(IploadbalancingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IploadbalancingStatus) DeepCopyInto(out *IploadbalancingStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IploadbalancingStatus.
func (in *IploadbalancingStatus) DeepCopy() *IploadbalancingStatus {
	if in == nil {
		return nil
	}
	out := new(IploadbalancingStatus)
	in.DeepCopyInto(out)
	return out
}
