//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatedatabaseDatabase) DeepCopyInto(out *PrivatedatabaseDatabase) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatedatabaseDatabase.
func (in *PrivatedatabaseDatabase) DeepCopy() *PrivatedatabaseDatabase {
	if in == nil {
		return nil
	}
	out := new(PrivatedatabaseDatabase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivatedatabaseDatabase) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatedatabaseDatabaseInitParameters) DeepCopyInto(out *PrivatedatabaseDatabaseInitParameters) {
	*out = *in
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatedatabaseDatabaseInitParameters.
func (in *PrivatedatabaseDatabaseInitParameters) DeepCopy() *PrivatedatabaseDatabaseInitParameters {
	if in == nil {
		return nil
	}
	out := new(PrivatedatabaseDatabaseInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatedatabaseDatabaseList) DeepCopyInto(out *PrivatedatabaseDatabaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PrivatedatabaseDatabase, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatedatabaseDatabaseList.
func (in *PrivatedatabaseDatabaseList) DeepCopy() *PrivatedatabaseDatabaseList {
	if in == nil {
		return nil
	}
	out := new(PrivatedatabaseDatabaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PrivatedatabaseDatabaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatedatabaseDatabaseObservation) DeepCopyInto(out *PrivatedatabaseDatabaseObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatedatabaseDatabaseObservation.
func (in *PrivatedatabaseDatabaseObservation) DeepCopy() *PrivatedatabaseDatabaseObservation {
	if in == nil {
		return nil
	}
	out := new(PrivatedatabaseDatabaseObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatedatabaseDatabaseParameters) DeepCopyInto(out *PrivatedatabaseDatabaseParameters) {
	*out = *in
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatedatabaseDatabaseParameters.
func (in *PrivatedatabaseDatabaseParameters) DeepCopy() *PrivatedatabaseDatabaseParameters {
	if in == nil {
		return nil
	}
	out := new(PrivatedatabaseDatabaseParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatedatabaseDatabaseSpec) DeepCopyInto(out *PrivatedatabaseDatabaseSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatedatabaseDatabaseSpec.
func (in *PrivatedatabaseDatabaseSpec) DeepCopy() *PrivatedatabaseDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(PrivatedatabaseDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatedatabaseDatabaseStatus) DeepCopyInto(out *PrivatedatabaseDatabaseStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatedatabaseDatabaseStatus.
func (in *PrivatedatabaseDatabaseStatus) DeepCopy() *PrivatedatabaseDatabaseStatus {
	if in == nil {
		return nil
	}
	out := new(PrivatedatabaseDatabaseStatus)
	in.DeepCopyInto(out)
	return out
}
