/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv1 "github.com/crossplane/crossplane-runtime/apis/common/v1"

// GetCondition of this InstallationTemplatePartitionScheme.
func (mg *InstallationTemplatePartitionScheme) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// GetDeletionPolicy of this InstallationTemplatePartitionScheme.
func (mg *InstallationTemplatePartitionScheme) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// GetManagementPolicies of this InstallationTemplatePartitionScheme.
func (mg *InstallationTemplatePartitionScheme) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// GetProviderConfigReference of this InstallationTemplatePartitionScheme.
func (mg *InstallationTemplatePartitionScheme) GetProviderConfigReference() *xpv1.Reference {
	return mg.Spec.ProviderConfigReference
}

// GetPublishConnectionDetailsTo of this InstallationTemplatePartitionScheme.
func (mg *InstallationTemplatePartitionScheme) GetPublishConnectionDetailsTo() *xpv1.PublishConnectionDetailsTo {
	return mg.Spec.PublishConnectionDetailsTo
}

// GetWriteConnectionSecretToReference of this InstallationTemplatePartitionScheme.
func (mg *InstallationTemplatePartitionScheme) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetConditions of this InstallationTemplatePartitionScheme.
func (mg *InstallationTemplatePartitionScheme) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// SetDeletionPolicy of this InstallationTemplatePartitionScheme.
func (mg *InstallationTemplatePartitionScheme) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

// SetManagementPolicies of this InstallationTemplatePartitionScheme.
func (mg *InstallationTemplatePartitionScheme) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// SetProviderConfigReference of this InstallationTemplatePartitionScheme.
func (mg *InstallationTemplatePartitionScheme) SetProviderConfigReference(r *xpv1.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// SetPublishConnectionDetailsTo of this InstallationTemplatePartitionScheme.
func (mg *InstallationTemplatePartitionScheme) SetPublishConnectionDetailsTo(r *xpv1.PublishConnectionDetailsTo) {
	mg.Spec.PublishConnectionDetailsTo = r
}

// SetWriteConnectionSecretToReference of this InstallationTemplatePartitionScheme.
func (mg *InstallationTemplatePartitionScheme) SetWriteConnectionSecretToReference(r *xpv1.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
