//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationTemplatePartitionScheme) DeepCopyInto(out *InstallationTemplatePartitionScheme) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationTemplatePartitionScheme.
func (in *InstallationTemplatePartitionScheme) DeepCopy() *InstallationTemplatePartitionScheme {
	if in == nil {
		return nil
	}
	out := new(InstallationTemplatePartitionScheme)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstallationTemplatePartitionScheme) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationTemplatePartitionSchemeInitParameters) DeepCopyInto(out *InstallationTemplatePartitionSchemeInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
	if in.TemplateName != nil {
		in, out := &in.TemplateName, &out.TemplateName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationTemplatePartitionSchemeInitParameters.
func (in *InstallationTemplatePartitionSchemeInitParameters) DeepCopy() *InstallationTemplatePartitionSchemeInitParameters {
	if in == nil {
		return nil
	}
	out := new(InstallationTemplatePartitionSchemeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationTemplatePartitionSchemeList) DeepCopyInto(out *InstallationTemplatePartitionSchemeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstallationTemplatePartitionScheme, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationTemplatePartitionSchemeList.
func (in *InstallationTemplatePartitionSchemeList) DeepCopy() *InstallationTemplatePartitionSchemeList {
	if in == nil {
		return nil
	}
	out := new(InstallationTemplatePartitionSchemeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstallationTemplatePartitionSchemeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationTemplatePartitionSchemeObservation) DeepCopyInto(out *InstallationTemplatePartitionSchemeObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
	if in.TemplateName != nil {
		in, out := &in.TemplateName, &out.TemplateName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationTemplatePartitionSchemeObservation.
func (in *InstallationTemplatePartitionSchemeObservation) DeepCopy() *InstallationTemplatePartitionSchemeObservation {
	if in == nil {
		return nil
	}
	out := new(InstallationTemplatePartitionSchemeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationTemplatePartitionSchemeParameters) DeepCopyInto(out *InstallationTemplatePartitionSchemeParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = new(float64)
		**out = **in
	}
	if in.TemplateName != nil {
		in, out := &in.TemplateName, &out.TemplateName
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationTemplatePartitionSchemeParameters.
func (in *InstallationTemplatePartitionSchemeParameters) DeepCopy() *InstallationTemplatePartitionSchemeParameters {
	if in == nil {
		return nil
	}
	out := new(InstallationTemplatePartitionSchemeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationTemplatePartitionSchemeSpec) DeepCopyInto(out *InstallationTemplatePartitionSchemeSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationTemplatePartitionSchemeSpec.
func (in *InstallationTemplatePartitionSchemeSpec) DeepCopy() *InstallationTemplatePartitionSchemeSpec {
	if in == nil {
		return nil
	}
	out := new(InstallationTemplatePartitionSchemeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstallationTemplatePartitionSchemeStatus) DeepCopyInto(out *InstallationTemplatePartitionSchemeStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstallationTemplatePartitionSchemeStatus.
func (in *InstallationTemplatePartitionSchemeStatus) DeepCopy() *InstallationTemplatePartitionSchemeStatus {
	if in == nil {
		return nil
	}
	out := new(InstallationTemplatePartitionSchemeStatus)
	in.DeepCopyInto(out)
	return out
}
