//go:build !ignore_autogenerated

/*
Copyright 2022 Upbound Inc.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPFrontend) DeepCopyInto(out *HTTPFrontend) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPFrontend.
func (in *HTTPFrontend) DeepCopy() *HTTPFrontend {
	if in == nil {
		return nil
	}
	out := new(HTTPFrontend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPFrontend) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPFrontendInitParameters) DeepCopyInto(out *HTTPFrontendInitParameters) {
	*out = *in
	if in.AllowedSource != nil {
		in, out := &in.AllowedSource, &out.AllowedSource
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DedicatedIpfo != nil {
		in, out := &in.DedicatedIpfo, &out.DedicatedIpfo
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DefaultFarmID != nil {
		in, out := &in.DefaultFarmID, &out.DefaultFarmID
		*out = new(float64)
		**out = **in
	}
	if in.DefaultSSLID != nil {
		in, out := &in.DefaultSSLID, &out.DefaultSSLID
		*out = new(float64)
		**out = **in
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.HTTPHeader != nil {
		in, out := &in.HTTPHeader, &out.HTTPHeader
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Hsts != nil {
		in, out := &in.Hsts, &out.Hsts
		*out = new(bool)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(string)
		**out = **in
	}
	if in.RedirectLocation != nil {
		in, out := &in.RedirectLocation, &out.RedirectLocation
		*out = new(string)
		**out = **in
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(bool)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPFrontendInitParameters.
func (in *HTTPFrontendInitParameters) DeepCopy() *HTTPFrontendInitParameters {
	if in == nil {
		return nil
	}
	out := new(HTTPFrontendInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPFrontendList) DeepCopyInto(out *HTTPFrontendList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HTTPFrontend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPFrontendList.
func (in *HTTPFrontendList) DeepCopy() *HTTPFrontendList {
	if in == nil {
		return nil
	}
	out := new(HTTPFrontendList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HTTPFrontendList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPFrontendObservation) DeepCopyInto(out *HTTPFrontendObservation) {
	*out = *in
	if in.AllowedSource != nil {
		in, out := &in.AllowedSource, &out.AllowedSource
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DedicatedIpfo != nil {
		in, out := &in.DedicatedIpfo, &out.DedicatedIpfo
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DefaultFarmID != nil {
		in, out := &in.DefaultFarmID, &out.DefaultFarmID
		*out = new(float64)
		**out = **in
	}
	if in.DefaultSSLID != nil {
		in, out := &in.DefaultSSLID, &out.DefaultSSLID
		*out = new(float64)
		**out = **in
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.HTTPHeader != nil {
		in, out := &in.HTTPHeader, &out.HTTPHeader
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Hsts != nil {
		in, out := &in.Hsts, &out.Hsts
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(string)
		**out = **in
	}
	if in.RedirectLocation != nil {
		in, out := &in.RedirectLocation, &out.RedirectLocation
		*out = new(string)
		**out = **in
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(bool)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPFrontendObservation.
func (in *HTTPFrontendObservation) DeepCopy() *HTTPFrontendObservation {
	if in == nil {
		return nil
	}
	out := new(HTTPFrontendObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPFrontendParameters) DeepCopyInto(out *HTTPFrontendParameters) {
	*out = *in
	if in.AllowedSource != nil {
		in, out := &in.AllowedSource, &out.AllowedSource
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DedicatedIpfo != nil {
		in, out := &in.DedicatedIpfo, &out.DedicatedIpfo
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.DefaultFarmID != nil {
		in, out := &in.DefaultFarmID, &out.DefaultFarmID
		*out = new(float64)
		**out = **in
	}
	if in.DefaultSSLID != nil {
		in, out := &in.DefaultSSLID, &out.DefaultSSLID
		*out = new(float64)
		**out = **in
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.HTTPHeader != nil {
		in, out := &in.HTTPHeader, &out.HTTPHeader
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Hsts != nil {
		in, out := &in.Hsts, &out.Hsts
		*out = new(bool)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(string)
		**out = **in
	}
	if in.RedirectLocation != nil {
		in, out := &in.RedirectLocation, &out.RedirectLocation
		*out = new(string)
		**out = **in
	}
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(bool)
		**out = **in
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = new(string)
		**out = **in
	}
	if in.Zone != nil {
		in, out := &in.Zone, &out.Zone
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPFrontendParameters.
func (in *HTTPFrontendParameters) DeepCopy() *HTTPFrontendParameters {
	if in == nil {
		return nil
	}
	out := new(HTTPFrontendParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPFrontendSpec) DeepCopyInto(out *HTTPFrontendSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPFrontendSpec.
func (in *HTTPFrontendSpec) DeepCopy() *HTTPFrontendSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPFrontendSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPFrontendStatus) DeepCopyInto(out *HTTPFrontendStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPFrontendStatus.
func (in *HTTPFrontendStatus) DeepCopy() *HTTPFrontendStatus {
	if in == nil {
		return nil
	}
	out := new(HTTPFrontendStatus)
	in.DeepCopyInto(out)
	return out
}
